# Generated by Django 6.0.2 on 2026-02-25 06:27

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อเอกสาร')),
                ('file', models.FileField(upload_to='documents/', verbose_name='ไฟล์เอกสาร')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่อัปโหลด')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_catego_slug_a504e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main_image', models.ImageField(upload_to=core.models.project_image_path)),
                ('description', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='projects/documents/')),
                ('description', models.CharField(blank=True, help_text='คำอธิบายเอกสารสั้นๆ', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.project_image_path)),
                ('image_type', models.CharField(choices=[('set1', 'Set 1'), ('set2', 'Set 2')], default='set1', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='core_projec_slug_fe29bd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='core_projec_categor_55bb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published'], name='core_projec_is_publ_c5c61b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project'], name='core_projec_project_7f88a1_idx'),
        ),
    ]
