# Generated by Django 6.0.2 on 2026-02-26 06:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_core_projec_is_publ_c5c61b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='core_projec_created_1f5557_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='core_projec_title_3ad890_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_projec_search__0f11ac_gin'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
