# Generated by Django 6.0.1 on 2026-03-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('hero', 'Hero + Gallery'), ('masonry', 'Masonry'), ('split', 'Split Layout')], default='grid', max_length=50),
        ),
    ]
