# Generated by Django 6.0.1 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_layout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='layout_type',
            field=models.CharField(choices=[('grid', 'Grid'), ('hero', 'Hero'), ('masonry', 'Masonry'), ('split', 'Split Layout'), ('magazine', 'Magazine Layout')], default='grid', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
