# Generated by Django 6.0.1 on 2026-04-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_layout_type_alter_project_status'),
        ('core', '0007_auto_20260408_1123'),
    ]

    operations = [
    ]
